branch-defaults:
  default:
    environment: langlearn-backend-env
  main:
    environment: langlearn-backend-env
    group_suffix: null
environment-defaults:
  backend-ecs:
    branch: null
    repository: null
  langlearn-backend-env:
    branch: null
    repository: null
global:
  application_name: language-learning-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
